### ISSUE TITLE
[Question] Difference between syntax highlighters

### ISSUE THREAD

**Issue by lonix1** [hangxingliu/vscode-nginx-conf-hint#10]
There are two of them, but what is the difference?

Which one is recommended / better ?

**Comment by yamlCase** [comment]
I'm trying to decide which highlighter to use myself.  It appears the "NGINX Configuration" by William Vokek is a fork of the other one I found, "nginx.conf" by shandoor which hasn't been touched in over a year.

**Comment by hangxingliu** [comment]
@lonix1 `sublime`, it is updated on 2020, but `original` from shandoor has long time no updates
