### ISSUE TITLE
Does it work on ssh remote VS Code projects? Installed but see no changes ..

### ISSUE THREAD

**Issue by palansher** [hangxingliu/vscode-nginx-conf-hint#14]
Hello! 

I see a liot positive reviews but I cannot get it worked. Nothing changed: no hints, no highlights ...

I set accociation with .conf files.
ext is installed: https://i.imgur.com/pREVede.png

Maybe some some triks required?

thank you!
Vladimir

**Comment by hangxingliu** [comment]
Hi, I just tested it on VS Code Remote, it can works well. But you don't need to install this extension on the remote, just at local. It can works well:
<img width="1417" alt="Screenshot 2021-11-14 at 18 41 34" src="https://user-images.githubusercontent.com/4303130/141677617-429b0c90-e7a4-4f0e-990c-d17b235a2453.png">
