### ISSUE TITLE
Comments inside map block directive not highlighted as comment on Sublime syntax

### ISSUE THREAD

**Issue by latipun7** [hangxingliu/vscode-nginx-conf-hint#15]
There's some little bug on brandonwamboldt/sublime-nginx#18 where comments inside map block directive not highlighted as comment.

![error](https://i.imgur.com/kRj7wNJ.png)

This extension still used old sublime syntax where that bug still applied.

**Comment by hangxingliu** [comment]
@latipun7 Hi Latif, I created a syntax generator in this repository. And generated a new syntax, I think you can have a try if you have time. You can overwrite your local `tmLanguage` file from this repo. The latest syntax:

<https://github.com/hangxingliu/vscode-nginx-conf-hint/blob/master/src/syntax/nginx.tmLanguage>

**Comment by latipun7** [comment]
> @latipun7 Hi Latif, I created a syntax generator in this repository. And generated a new syntax, I think you can have a try if you have time. You can overwrite your local `tmLanguage` file from this repo. The latest syntax:
> 
> https://github.com/hangxingliu/vscode-nginx-conf-hint/blob/master/src/syntax/nginx.tmLanguage

I already tried it, Great, nice, this is a lot better 👍 I like it. I prefer this theme over the current `sublime` or `original`.

I did copy the content of that file, then overwrites in my local `C:\Users\USER\.vscode\extensions\hangxingliu.vscode-nginx-conf-hint-0.2.0\syntaxes\original.nginx.tmLanguage`, then select the settings to use original theme. Reload VSCode, it's works nicely. But there's always showed up this error when I open VSCode in nginx files:
![error](https://i.imgur.com/036CPfs.png)
The error always showed up, but the syntax highlighting is correct and nice 🥇

**Comment by hangxingliu** [comment]
@latipun7 
You can add line `<!-- vscode-nginx-conf-hint { syntax-type: original }  -->` after `<?xml version="1.0" encoding="UTF-8"?>` for temporary fix.

And I will release the next version in the next two weeks, and the new syntax will be included in the new version.

**Comment by latipun7** [comment]
Oh yeah, great works. Thank you ✨
