### ISSUE TITLE
Enable for conf.j2 files

### ISSUE THREAD

**Issue by rightaway** [hangxingliu/vscode-nginx-conf-hint#21]
If you're templating an nginx config file like `nginx.conf.j2` (such as in various provisioning tools that use jinja) the autocompletion features don't work. This extension is only enabled for `.conf` files. Can you enable it also for `.conf.j2` files?

**Comment by hangxingliu** [comment]
@rightaway can use VSCode configuration `files.associations` to resolve this problem.
see example in this commit: d69a269b158368642ab1e2ed7796588200399666
