### ISSUE TITLE
Release on OpenVSX

### ISSUE THREAD

**Issue by Sir-Photch** [hangxingliu/vscode-nginx-conf-hint#54]
Hi, this is not necessarily a bug report as it is a feature request.

Do you think it would be possible to upload this extension to the [OpenVSX](https://open-vsx.org/) registry? This way, users of [VSCodium](https://github.com/VSCodium/vscodium) could also benefit from this extension without depending on the extension store of Microsoft.

**Comment by hangxingliu** [comment]
It will be released on OpenVSX on the next version in March 2024.

**Comment by hangxingliu** [comment]
Hi I just released the new version and just published on OpenVSX:
<https://open-vsx.org/extension/hangxingliu/vscode-nginx-conf-hint>

**Comment by Sir-Photch** [comment]
Many thanks!!
