### ISSUE TITLE
Use when nginx.conf appears anywhere in filename

### ISSUE THREAD

**Issue by rightaway** [hangxingliu/vscode-nginx-conf-hint#7]
I'm creating `nginx.conf.ext` where `ext` can be any extension, but then I lose the formatting. This extension should work if nginx.conf is anywhere in the filename. If it's not possible to do that, the configuration should take a list of filenames it should work on so we can add it manually.

**Comment by hangxingliu** [comment]
I will release a new version in recent days and your issue will be fixed in it
