### ISSUE TITLE
Can I upgrade to the latest version

### ISSUE THREAD

**Issue by linjialiang** [hangxingliu/vscode-nginx-conf-hint#8]
> Can I upgrade to the latest version

**Comment by hangxingliu** [comment]
Of course, And I will release the latest version in recent days

**Comment by linjialiang** [comment]
> Thank you very much !

I have one more question for you:
Does vscode's nginx extension only need to install `hangxingliu/vscode-nginx-hint`

**Comment by hangxingliu** [comment]
Yes, only this extension. because of the formatter and the syntax of Nginx configuration is integrated into this extension.

**Comment by linjialiang** [comment]
Thank you ！
