### ISSUE TITLE
[Feature Request] Show URL for nginx docs

### ISSUE THREAD

**Issue by lonix1** [hangxingliu/vscode-nginx-conf-hint#9]
It would be nice for the popup to also show the URL to the nginx docs site. So we can click the link and read the documentation.

e.g. popup for `location` will show a link to the [appropriate documentation](https://nginx.org/en/docs/http/ngx_http_core_module.html#location).

**Comment by hangxingliu** [comment]
this feature has been add into <https://github.com/hangxingliu/vscode-nginx-conf-hint/releases/tag/0.2.0>

**Comment by lonix1** [comment]
:smile: :smile: :smile:
